---
title: "Working data preparation for AP prediction models"
author: "Bernd Panassiti"
date: 'created: 20.07.2015, last modified: `r format(Sys.Date(), format="%d.%m.%Y")`'
output:
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    toc: yes
    toc_depth: 5
  html_document: default
  word_document: default
subtitle: Clustering of monitoring sites
header-includes: \usepackage{graphicx}
---


## Introduction
This script prepares the rawdata for AP prediction models. 


```{r setup, warning=FALSE, echo=FALSE}
library(knitr) # for creating html-file
opts_knit$set(root.dir='../') # definining working directory; or normalizePath('../')
opts_chunk$set(fig.align='center') # aligns all figures
opts_chunk$set(echo=FALSE) # suppresses r-code
opts_chunk$set(message=FALSE) # suppresses library outputs
opts_chunk$set(warning=FALSE) # suppresses library warnings
opts_chunk$set(dev='pdf')

```

```{r load}
rm(list=ls(all=TRUE))
source("r-code/00_settings.r")
source("r-code/00_helper_functions.r")
load(file="data/AP_rawdata.Rdata")
set.seed(2015)
```


### Environment combined


sitesCluster beziehen sich nur auf bereits bonitierte Apfelanlagen.  

```{r env_combined_cluster}
# combined at site (orchard) scale
sitesAspect   <- aggregate(aspect~site_id,demSlopeAspect,mean)
sitesSlope    <- aggregate(slope~site_id,demSlopeAspect,mean)
sitesAltitude <- aggregate(altitude~site_id,demAltitude,mean)

orchardRegionClimate <- as.data.frame(sitesClimate[,c("id","region","ZAMGclimate")])
orchardRegionClimate <- orchardRegionClimate[which(orchardRegionClimate$id %in% sitesAspect$site_id),]
orchardRegionClimate <- orchardRegionClimate[order(orchardRegionClimate$id),1:3]

sitesCluster <- data.frame(cbind(orchardRegionClimate,sitesAltitude$altitude,sitesAspect$aspect,sitesSlope$slope))
colnames(sitesCluster) <- c("id","region","climate","altitude","aspect","slope")

# weather stations - weather stations meta data from South Tyrol obtained from EURAC
df <- data.frame(sitesWeatherStationsClimate[sitesWeatherStationsClimate$apple==1,c("NUMMER","region","ZAMGclimate","HOEHE")])
df <- df[,1:4]
colnames(df) <- c("id","region","climate","altitude")
stationsCluster <- data.frame(df,sitesWeatherStationsSlopeAspect[,2:3])
```
 




## Save
```{r save}
save(
SouthTyrol,
sitesWeatherStations,  # weather stations meta data from South Tyrol extracted from "DataBaseAlpEnvEURAC" package

# data for clustering
orchardRegionClimate,
sitesAspect,sitesSlope,sitesAltitude,
sitesCluster,stationsCluster,
sitesCentroid,

# data for modelling
responseAP,
demSlopeAspect,
demAltitude,
file="data/AP_workingdata.Rdata"
)
```


